import re, sys

# Raw lyric list generated by scraper
UNFILTERED_INPUT="songLyrics.txt"
# Save filtered lyric list here
FILTERED_OUTPUT="filteredSongLyrics.txt"

# List of regex blacklist rules for lyrics.
BLACKLIST_PATTERN_FILE="blacklistPatterns.txt"

# Characters to remove form the start and ends of lyrics.
LEADING_CHARS_TO_REMOVE="^[,.?]" # Start of lyric
TRAILING_CHARS_TO_REMOVE="[,]+$" # End of lyric

blackListRegex = None
with open(BLACKLIST_PATTERN_FILE) as blacklistFHandle:
  patternList = blacklistFHandle.readlines()
  blackListRegex = re.compile('|'.join(patternList))

blacklisted=0
filteredLyricList = []
with open(UNFILTERED_INPUT) as unfilteredFHandle:
  unfilteredList = unfilteredFHandle.readlines()
  filteredLyricList = [lyric for lyric in unfilteredList if not blackListRegex.match(lyric)]
  filteredLyricList = [re.sub(LEADING_CHARS_TO_REMOVE, '', lyric) for lyric in filteredLyricList] 
  filteredLyricList = [re.sub(TRAILING_CHARS_TO_REMOVE, '', lyric) for lyric in filteredLyricList] 

with open(FILTERED_OUTPUT, 'w') as filteredFHandle:
  for lyric in filteredLyricList:
    filteredFHandle.write(lyric)
    




